### PR TITLE
Correct base qualities if reads are overlapped

### PR DESCRIPTION
**Pull request by alumi**
`samtools mpileup` has a functionality to correct base qualities if reads are overlapped.

```
@SQ	SN:seq1	LN:100
R001	99	seq1	3	60	2S8M	=	1	8	AATTGGCCAA	AABBCCDDEE
R001	147	seq1	3	60	8M2S	=	1	-8	TTGGCCAATT	AABBCCDDEE
```

```
> samtools mpileup -BQ0 overlap.bam
seq1	3	N	2	^]T^]t	b!
seq1	4	N	2	Tt	b!
seq1	5	N	2	Gg	d!
seq1	6	N	2	Gg	d!
seq1	7	N	2	Cc	f!
seq1	8	N	2	Cc	f!
seq1	9	N	2	Aa	h!
seq1	10	N	2	A$a$	h!
```

(`!` stands for 0 quality in phred-33 score)

This reduces the depth of piles if threshold of base quality is greater than 0.

This PR adds similar function for `cljam.pileup.mpileup`.

### CODE REVIEW

**Comment by alumi** [comment]
Sorry, I found a bug in this. I'll fix it soon.

**Comment by alumi** [comment]
So sorry, I need another fix.

**Comment by alumi** [comment]
I've added some changes to make it more modular and composable.
I also modified intermediate data structure that `cljam.pileup.mpileup/pileup*` returns.

`cljam.pileup.mpileup/pileup` now does three steps: filtering reads, piling up bases and filtering bases.
It can be easily reimplemented using `cljam.pileup.mpileup/pileup*` and some other functions.

This PR adds some more conditions for filtering reads and bases.
- Secondary or supplementary alignments are not used.
- Mapped but not properly paired alignments are not used.
- Overlapping R1/R2 paired-end alignments are merged to one of them.
- Bases with low read-quality are not used.
- Bases with low map-quality are not used.

**Comment by totakke** [comment]
Good. Thank you.

**Pull request merged**
