### PR TITLE
Fix to parse VCF meta info key with space

### PR DESCRIPTION
**Pull request by nuggetoriniku**

### CODE REVIEW

**Comment by alumi** [comment]
Hi @nuggetoriniku, thank you for the PR 👍 but I don't think I understand what this PR is trying to solve. Is this for fixing a violation of the VCF spec? If so, would you provide a link to the spec and add a test case for it?

**Comment by nuggetoriniku** [comment]
@alumi
Thank you for the comment.

The case I try to resolve is following. ( provided by [gnomAD](https://gnomad.broadinstitute.org/).[^1] )
```vcf
##VEP version: v101
##dbSNP version: b154
##age distributions: bin_edges=[30.0, 35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 65.0, 70.0, 75.0, 80.0], bin_freq=[1428, 1606, 1905, 3228, 4577, 3924, 3656, 3194, 2153, 1283], n_smaller=3760, n_larger=454
```
VCF spec is probably not define this case.
But ... I would like to handle it on the outside as a rare case. :thinking:
[^1]: v3.1.2 Genomes VCF

**Comment by nuggetoriniku** [comment]
> @alumi Thank you for the comment.
> 
> The case I try to resolve is following. ( provided by [gnomAD](https://gnomad.broadinstitute.org/).[1](#user-content-fn-1-707269e67ccabaae8c22a19360eeb85c) )
> 
> ```
> ##VEP version: v101
> ##dbSNP version: b154
> ##age distributions: bin_edges=[30.0, 35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 65.0, 70.0, 75.0, 80.0], bin_freq=[1428, 1606, 1905, 3228, 4577, 3924, 3656, 3194, 2153, 1283], n_smaller=3760, n_larger=454
> ```
> 
> VCF spec might not define this case. But ... I would like to handle it on the outside as a rare case. 🤔
> ## Footnotes
> 
>     1. v3.1 Genomes VCF [↩](#user-content-fnref-1-707269e67ccabaae8c22a19360eeb85c)

**Comment by nuggetoriniku** [comment]
In the latest version of the data, the above whitespaces have been changed to "_" and do not cause any problems.

**Pull request closed without merging**
